CREATE DATABASE IF NOT EXISTS api CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS frontend CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS auth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'dev'@'%' IDENTIFIED BY '12345678';

GRANT ALL PRIVILEGES ON api.* TO 'dev'@'%';
GRANT ALL PRIVILEGES ON frontend.* TO 'dev'@'%';
GRANT ALL PRIVILEGES ON auth.* TO 'dev'@'%';

FLUSH PRIVILEGES;